apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-app
  namespace: argocd
spec:
  destination:
    name: 'ci-app'
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/crnksl/argocd-nginx.git'
    targetRevision: HEAD
    path: 'kubevela'
  project: default
