name: CI Pipeline with KubeVela and ArgoCD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    

      - name: Apply KubeVela Application
        run: |
          kubectl apply -f argocd-nginx/kubevela-app.yaml
          
      - name: Sync with ArgoCD
        run: |
          argocd app sync ci-app
